version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  superset:
    image: apache/superset:latest
    restart: unless-stopped
    environment:
      SUPERSET_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      RESULT_BACKEND: ${RESULT_BACKEND}
    depends_on:
      - db
      - redis
    volumes:
      - ./docker:/app/docker
      - superset_home:/app/superset_home
    ports:
      - "8088:8088"
